### PR TITLE
Automatically hide plug-ins without compatible instance

### PR DESCRIPTION
**Pull request by mottosso**
I've undone the [previous PR](https://github.com/pyblish/pyblish-lite/pull/89) and opened this one up again. It does what it's supposed to, it just needs some cleanup and refactoring. I'll try and elaborate on details soon and will just leave this open for now.

### CODE REVIEW

**Comment by mottosso** [comment]
Hey @p4vv37, sorry for the delay!

When you have a moment, would you be able to address notes on this? Let me know and we can get this mergable; it's such a great feature it'd be a shame not to see it merged.

**Comment by p4vv37** [comment]
Hey

I've been quite busy lately and did not have enough time, but I hope I'll be able to take care of this during next week or two. 
I do remember about it and I hope so I'll be able to finish it soon.

**Comment by mottosso** [comment]
Excellent, I'll put some notes in. Let's make it happen! :)

**Comment by mottosso** [comment]
I made my notes with code in the form of a pull request here.

- https://github.com/p4vv37/pyblish-lite/pull/2

There wasn't as much astray as I had initially thought.

**Pull request closed without merging**
