### PR TITLE
adds user friendly publish tab.

### PR DESCRIPTION
**Pull request by larsbijl**

### CODE REVIEW

**Comment by larsbijl** [comment]
publish

**Comment by mottosso** [comment]
Wow. :) Taking a closer look in the morning, looks really great!

**Comment by mottosso** [comment]
Current up-to-date look.



Next I think we should have a look at making the comment-box appear when the user hits "Publish". How about having it appear regardless of the tab you are in? I'll be on other things today (more CS courses) but can help out more tomorrow onwards. Are you working on this any more today?

**Comment by larsbijl** [comment]
this last set of changes has broken the terminal view.
shot1

**Comment by mottosso** [comment]
Yeah, I got that too. Not sure what happened. Can you investigate?

**Comment by larsbijl** [comment]
fixed it.

will push soon

**Comment by mottosso** [comment]
Ok, PR submitted.

I think it's usable now, will merge if you accept your PR.

About the automatic toggling to Overview on problems, I've got an idea for this and will look at that next. In a nutshell, I think that rather than forcefully toggling to Overview, a heads-up message should appear, giving the user an option to toggle to that view. At the moment, it's a bit abrupt and confusing I think.

**Comment by larsbijl** [comment]
oke, that make sense

PR merged

**Comment by mottosso** [comment]
@larsbijl could you post a gif of the GUI in action at the moment? I can't post files from where I am at the moment, and it would be good to get a good record of where we are at for the forums.

**Pull request merged**
