### PR TITLE
Groundwork for #22

### PR DESCRIPTION
**Pull request by mottosso**
Have a play with this if you can @larsbijl, it's possible the logic has broken. There are some tests, but they are quite rudimentary and likely doesn't cover all aspects.

Adding a validate button is now a function-call away.

### CODE REVIEW

**Comment by larsbijl** [comment]
amazing. i'll have a look later tonight

**Comment by mottosso** [comment]
Ok, I discovered a subtle difference, one that might even be in QML.

Before, plug-ins were run like this.

**Reset** Orders (-0.5 - 0.5)

```bash
Order    : Plugin
---------|-------------
# -1     : PreCollectorA
# -0.75  : PreCollectorB
0        : Collector           <----
# 1      : Validator
# 2      : Extractor
```

**Publish** Orders (0.5 - end)

```bash
Order    : Plugin
---------|-------------
# -1     : PreCollectorA
# -0.75  : PreCollectorB
# 0      : Collector
1        : Validator          <----
2        : Extractor
```

Which as you can see, ignores anything before collection. In the case of the `--debug` mode, the SimplePlugin1, 2 and 3.

**Comment by larsbijl** [comment]
this seems to be working a treat. if anything it seems to be wayyy faster!

**Comment by mottosso** [comment]
> if anything it seems to be wayyy faster!

Yeah, well. That's the beauty of adding an artificial delay. You can lower it to make things faster! ;)

Play around with the environment variable `PYBLISH_DELAY=1`. It's a scale-factor. Setting it to 0 will run everything as fast as possible. At a cost, that will become apparent when you try. :)

**Comment by larsbijl** [comment]
this is working well for me so far. and i've implemented validate and it seems to work

**Comment by larsbijl** [comment]
one weird behaviour i'm noticing is that on reset it tries to maintain the instance selection. but it forgets one entry. it's seems to pick one at random.

so i'll have selected all the instances, i validate and reset and one of them will be unselected

**Comment by mottosso** [comment]
Ah, makes sense. It's storing history based on the name of instances, and instances could potentially have the same name.

Should we try and store based on index instead?

Could you PR your validator implementation to the mottosso account? Would you like to finish it?

**Comment by larsbijl** [comment]
can we store based on name and family?

ok i'll create a PR send it your way.

**Comment by mottosso** [comment]
> can we store based on name and family?

I suppose.. but can't you technically have multiple instances of the same name *and* family? I smell confusion at some point.

Storing by position doesn't play as well against instances disappearing or being added or reordered inbetween resets, but maybe that's at least consistent? Maybe discard history if the amount of items changes?

**Comment by larsbijl** [comment]
I can't think of a instance where i'd have 2 instances having the same name also being the same family.
but i guess fundametaly it's possible if you're setting up your collectors weird.

I'm using the `CollectSorting` collector so re-ordering is in the cards for me.

**Comment by mottosso** [comment]
> I'm using the CollectSorting collector so re-ordering is in the cards for me.

That should be fine, so long as it's reordering during collection. If you're reordering after that point, then you're into undefined behaviour land anyway.

I meant more, if it's reordering differently between two resets.

But maybe you're right, coupling family and name should cover most aspects. Having two of same name and family can happen though, if someone has an alternate workflow, such as storing custom data to determine where and how things are published, rather than the standard family/name. For those people, the GUI could get quite annoying.

Maybe use this as a default, and allow an option to uncheck "Remember toggles" to disable it when going rouge.

**Comment by mottosso** [comment]
Sweeeet.

I'll have a look at the out-of-focus confirmation feature. But for now, I'd consider this feature at 1.0.

Ready to merge?

**Comment by larsbijl** [comment]
yes this feature is good to go but it's not 1.0 fully.

currently dealing with error is still a pain. unlike in the qml version where we can dig into the plugin's view and see specific details.

if we can come up with something like that then we are cooking with gas.

**Comment by mottosso** [comment]
> yes this feature is good to go but it's not 1.0 fully.

No no, I meant 1.0 for this particular feature, the validate button. Not 1.0 for the GUI, the things you mention are indeed missing.

I've got an idea for a detail view that I'd like to implement, but today is a bit more busy so I can't promise results. If you're interested, I could mock up what I have in mind for you to get started? It's Houdini-inspired.

**Comment by larsbijl** [comment]
lets do it!

**Pull request merged**
