### PR TITLE
GitHub/pypeclub/openpype updates

### PR DESCRIPTION
**Pull request by gitwipo**
Hello,

Here is the pull request with all changes from pype and later openpype added. 

There are a lot of changes. This is a one time case. The next pull request will be smaller and might also be more selective what will get added from [openpype](https://github.com/pypeclub/OpenPype/tree/develop/openpype/tools/pyblish_pype). It is the follow up pull request from: [Update from pype #109](https://github.com/pyblish/pyblish-lite/pull/109)

I ported the changes from openpype using patches (excluding any renaming or import updates)
```bash 
# Do in openpype repository
git format-patch -<commits> openpype/tools/pyblish_pype
# Do in pyblish_lite repository
find -type f -name '*.patch' -exec sed -i 's/openpype\/tools\/pyblish_pype/pyblish_lite/g' {} \;
git apply --ignore-space-change --ignore-whitespace patch.diff
```
This does work quite well for most changes.  Some patches need a bit fixing.

I resolved all conflicts with the master branch, mainly using pype/openpype parts.
I tried to address most of the comments made before.

I did not work on getting the tests passing yet.

## Purpose
- Get all additions from pype/openpype in.
- Update so new features from openpype can be ported more easily.

## Additions
- Add window animation ([seems to be actively worked on in openpype](https://github.com/pypeclub/OpenPype/commits/develop/openpype/tools/pyblish_pype))
- Add qt threading to allow updating the ui while plugins are processed
- Add `yapf` formatting with custom config to keep the prevailing style (I think this is easier than manual matching the formatting)
- Add `flake8` and `mypy` config
- Add `dev-requirements.txt` for development packages

## Updates
- Update `requirements.txt`
- Docker
  - Update docker image to newer `ubuntu 20.04 lts` release
  - Use pip to install dependencies.
  - Include basic `flake8` and `mypy` linting
- Sort instances by family
- Visual group plugins by pyblish order

## Removes
- Remove `Qt.py` from vendor
- Remove `six` from vendor

I could have missed additions and updates that are made in the description.

### CODE REVIEW

**Comment by mottosso** [comment]
Hello @gitwipo, nice work. Aside from backwards compatibility needing to remain intact, and tests needing to pass, the main crux of a merge this big is that there needs to be at least 1 person capable of maintaining it. When issues arise, someone needs to be here to tackle those. At this point in time, that's me, as I've got an understanding of what's in here currently.

If we merge this, I can do my best in supporting it but there is too many changes for me to confidently do so. So the question is, are you in a position to take over maintainence of this repository? Primarily involving responding to issues and figuring out solutions to bugs.

**Comment by mottosso** [comment]
Very nice. We could/should embed six.py, it's a standalone tiny library.

In fact, it's already embedded? 🤔 Can you link to where it's turned into a dependency @hannesdelbeke?
- https://github.com/pyblish/pyblish-lite/tree/master/pyblish_lite/vendor

**Comment by mottosso** [comment]
Does it mean the end-user will have to install six? If so then it should definitely be included. Any dependency that can be included should be included, the user should have to do as little as possible.

**Comment by gitwipo** [comment]
Yes six was removed in the pype club code. It can be readded again. As mentioned above it is one file so I also don't see a issue readding it into vendors.

First I will add one more small fix from open pype for the newly added animation.

After that the test have to work again. So for that a little help would be nice.

I didn't find a good guide how to update the test to work the introduced `MainThreadProcess`. So if some has an idea or a link how to make nose tests work threads, please write a comment.

**Comment by gitwipo** [comment]
Hello,

sorry we decided to switch to `pyblish qml`. Therefore won't work on this.

As mentioned before this PR dose change a lot and derivatives from the orginal code. So it is hard to maintain. And also openpype are no longer working on the pyblish lite embed fork. 

So closing.

Thanks, again for taking the time to look at it.

**Comment by mottosso** [comment]
Thanks for the heads up!

**Pull request closed without merging**
