### PR TITLE
Unchecking instances hides plugins that operate on them, simplified plugins matching

### PR DESCRIPTION
**Pull request by p4vv37**
Also: simplified families matching, based on pyblish-bese elements
Uses plugins_by_families of pyblish-base to match plugins now

### CODE REVIEW

**Comment by mottosso** [comment]
Looking good @p4vv37! Once you're happy with this, version it up and I'll make a new release.

**Comment by p4vv37** [comment]
Wel, I've updated the Patch, but now I'm not sure if I should not update minor instead

**Comment by mottosso** [comment]
I'm not too picky; so long as it's not a major release as I'd like to preserve those for breaking changes.

This looks fine to me.

**Comment by mottosso** [comment]
I've missed merging this. Could you let me know when you are happy with the current state and I'll merge as soon as I'm back at a computer.

To avoid adding further commits to it, you should push to a different branch.

**Comment by mottosso** [comment]
This works for me, merging this!

**Comment by p4vv37** [comment]
Hi, sorry for not replying.
If it's allright, then great :)

**Comment by mottosso** [comment]
No problem @p4vv37, I actually undid this merge.

- https://github.com/pyblish/pyblish-lite/pull/91

There are some issues we'll need to get through before merging.

**Pull request merged**
