### PR TITLE
Work in progress on #25

### PR DESCRIPTION
**Pull request by mottosso**

### CODE REVIEW

**Comment by mottosso** [comment]
This also includes the new comment field, which is enabled by the Context having a `comment` data member. If it's empty, an empty comment box appears. Whatever it contains is added in place of placeholder text.

**Comment by mottosso** [comment]
Let me know what you think of the graphics of the details view @larsbijl, activated by middle-clicking on an instance/plug-in.

**Comment by larsbijl** [comment]
I think making the middle click window a  but wider will not go a miss but I like the idea.
we will need to have line wrapping and a ability to keep it on so we can read logs.

**Comment by mottosso** [comment]
Ok, I've reduced the scope of this feature to only show a minimal amount of information. I'll implement a full Perspective like in QML, I think that's the way forward.

Let me know what you think.

**Comment by larsbijl** [comment]
I like the design yet having those log entries is what would make that feature invaluable.

**Comment by mottosso** [comment]
Because the log can get quite large, I'm thinking it's better suited to its own tab.

Maybe print just the last 3-4 log entries in the popup, and keep full details for the tab?

**Comment by larsbijl** [comment]
so we should create a extra tab like in qml for the plugins details? if so that I agree the popup doesn't need any more details.

**Comment by mottosso** [comment]
Yeah, that's what I'm thinking.

**Comment by larsbijl** [comment]
cool, then i think this is ready to merge

**Pull request merged**
