### PR TITLE
fixed bug

### PR DESCRIPTION
**Pull request by cuckon**
fixed a bug that caused by incorrect argument of `traceback.format_exc()`

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks for this! Merging as soon as Travis is happy.

**Comment by mottosso** [comment]
Take your time, let me know when you're happy. This looks like a solid fix to me so far.

**Comment by cuckon** [comment]
> Take your time, let me know when you're happy. This looks like a solid fix to me so far.

Hi @mottosso I think I'm happy with it right now. Let me know if there's anything else I need to do.

**Comment by mottosso** [comment]
That's it, thanks again @cuckon. Making a new release now, will be available on PyPI in a few minutes.

**Pull request merged**
