### PR TITLE
fixed issues with lambda not working.

### PR DESCRIPTION
**Pull request by larsbijl**

### CODE REVIEW

**Comment by larsbijl** [comment]
this will close #17

**Comment by mottosso** [comment]
Thanks for this. I'd rather not mix lambdas and partial() though, can you find a way to make it work with lambda you think? It's either that, or we use partial throughout.

**Comment by larsbijl** [comment]
not sure what the original issue with the lambda's was. but it wasn't currying the function properly.

i'll have a other look tomorrow. otherwise i think partial might be safer.

**Comment by larsbijl** [comment]
now using lamdba instead of partial

**Comment by mottosso** [comment]
Hm, this shouldn't work. :S The reason I had the obscure looking `c=context` was because of how lamba's work when used in a loop like this. I would expect `action` to be the same for each lambda, and that when you actually come to run it, no matter which action you select, it would always run the same one.

Could you confirm that you can actually have two different actions, and that they both do what they are supposed to?

I'll see about getting some travis tests for this as well.

**Comment by larsbijl** [comment]
correct. it seems to always pick up the latest.

modifed it back to using the default args but not using the first `checked` argument.

this seems to work and each plugin is different.

**Comment by mottosso** [comment]
Cool.

Oh and again, could you make sure you commit changes with your GitHub email set? Looks like the commits are owner-less at the moment.

If you retrospectively change the owner, if you then *force* push, all should update accordingly, even this PR. Force pushing is fine, so long as no one else has forked your repo and continued working off of it.

**Comment by larsbijl** [comment]
Done.
also made it 1 commit.

**Comment by mottosso** [comment]
Awesome, thanks.

**Pull request merged**
